name: Cache Local
on:
  workflow_dispatch:

jobs:
  build:
    runs-on:  windows-latest
    steps:
    - uses: actions/cache@b13b69db368ea1b3533a8556b4066e7063650f48
      id: cache
      with:
        path: /tmp/datacache
        key: windows_cache_50_9
    - if: steps.cache.outputs.cache-hit != 'true'
      run: |
        rm -rf /tmp/datacache
        mkdir -p /tmp/datacache
        for y in {0..30};do openssl rand -out /tmp/datacache/data$y  -base64 $(( 50 * 2**20 * 3/4 )); done 
        du -sh /tmp/datacache
