name: Cache Local
on:
  workflow_dispatch:

jobs:
  build:
    runs-on:  ubuntu-latest
    steps:
    - uses: actions/cache@5c0fd51138cc2b5fd24d728a970b8841df47464d
      id: cache
      with:
        path: /tmp/datacache
        key: ubuntu_cache_50_9
    - if: steps.cache.outputs.cache-hit != 'true'
      run: |
        rm -rf /tmp/datacache
        mkdir -p /tmp/datacache
        for y in {0..9};do openssl rand -out /tmp/datacache/data$y  -base64 $(( 50 * 2**20 * 3/4 )); done 
        du -sh /tmp/datacache
